// Shot mode: VIPER's real second muzzle flash over the lingering sparks, blood and dust of its first hit.
__sr.hold(false);
__sr.reset();
__sr.start();
__sr.bot(false);
const g = __sr.G;
g.zombies.length = g.rounds.length = g.timers.length = 0;
g.loot.length = g.lootFly.length = 0;
g.spawnCd = g.railCd = g.waveCd = 1000000;
g.helis[0].cd = 1000000;
__sr.sim(8);
__sr.frames(240);
const h = g.helis[0], {W, H} = __sr.stats();
h.x = g.camX + W * 0.55;
h.y = g.camY + H * 0.7;
h.vx = h.vy = 0;
h.alt = 25;
h.cd = 0;
const z = __sr.spawn(0, h.x - g.camX + 36, h.y - g.camY - 65);
z.hp = 9999;
h.hd = Math.atan2(z.x - h.x, -(z.y - h.y));
__sr.order(0, 'attack', z);
for (let i = 0; i < 40 && g.shots < 2; i++) __sr.sim(1 / 60);
if (g.shots !== 2 || g.hits < 1 || h.flash <= 0) throw new Error('Shot did not capture real muzzle/impact effects');
__sr.frames(1);
__sr.hold(true);
